CREATE TABLE users (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_name  VARCHAR(50)  NOT NULL,
                       email      VARCHAR(255) NOT NULL UNIQUE,
                       password   VARCHAR(255) NOT NULL,
                       first_name VARCHAR(60)  NOT NULL,
                       last_name  VARCHAR(60)  NOT NULL,
                       role       VARCHAR(20)  NOT NULL CHECK (role IN ('STUDENT','INSTRUCTOR','ADMIN')),
                       is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
                       created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
